export const QLKC_C3_GIAONHAN_TEMCHI = {
  id: null,
  soluong: null,
  loai: null,
  donvi_tinh: null,
  don_vi_giao: null,
  don_vi_nhan: null,
  nguoi_nhan: null,
  nguoi_giao: null,
  ngay_giao: null,
  ngay_nhan: null,
  trang_thai: null,
  loai_bban: null,
  ten_nguoi_giao: null,
  ten_nguoi_nhan: null,
  ten_pb: null,
  ten_dv: null,
};
