export const QLKC_BBAN_BANGIAO_KIM = {
  id_bienban: null,
  id_kim: null,
  so_luong: null,
  don_vi_giao: null,
  don_vi_nhan: null,
  nguoi_nhan: null,
  nguoi_giao: null,
  ngay_giao: null,
  ngay_nhan: null,
  loai_bban: null,
  noi_dung: null,
  trang_thai: null,
  ten_nguoi_giao: null,
  ten_nguoi_nhan: null,
};
